### ISSUE TITLE
Urgent for a dataset

### ISSUE THREAD

**Issue by sunxiaowu** [gagolucasm/DL_CIMT_and_plaque_estimation#3]
hello, I can't find REGICOR  database,could you please send me a copy, just for code use, never for external transmission, thank you.
<img width="918" alt="a" src="https://user-images.githubusercontent.com/15603025/212001886-c957a7bf-8bd3-4255-ab56-bba0c3bc692c.PNG">

**Comment by gagolucasm** [comment]
Hello, unfortunately, I cannot share the database since I am not the owner. You'll need to request access here: https://regicor.cat/en/. Good luck, and thanks for your interest!
